title: blog title
author: unknowncker
email: notreal@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  this blog is only to test and learn github services

# social links
twitter_username: none
github_username:  unknowncker

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
