title: web page
author: unknowncker
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  this site dont have any thing intersting i just testing GitHub services

# social links
github_username:  https://github.com/unknowncker

show_excerpts: true # set to false to remove excerpts on the homepage

theme: cayman
